- name: Instalar php
  apt:
    pkg: php7.4

- name: Instalar php-fpm
  apt:
    pkg: php7.4-fpm
  
- name: Copiar info.php
  copy:
    src: info.php
    dest: /{{item["datos"]["documentroot"]}}/
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - "{{virtualhosts}}"

