- name: Instalar nginx
  apt:
    pkg: nginx
    state: present

- name: Configuración de virtualhost
  template: 
    src: etc/nginx/sites-available/vhost.j2
    dest: /etc/nginx/sites-available/{{item["name"]}}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{virtualhosts}}"

- name: Crear documentroot en caso de que no exista
  ansible.builtin.file:
    path: /{{item["datos"]["documentroot"]}}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items: "{{virtualhosts}}"

- name: Añadir enlace simbólicos de los virtualhosts en sites-enabled.
  file:
    src: /etc/nginx/sites-available/{{item["name"]}}.conf
    dest: /etc/nginx/sites-enabled/{{item["name"]}}.conf
    state: link
    mode: 0755
  with_items: "{{virtualhosts}}"

- name: Copiar index.html
  copy:
    src: index_{{item["name"]}}.html
    dest: /{{item["datos"]["documentroot"]}}/index.html
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{virtualhosts}}"

- name: Copiar nuevodirectorio
  copy:
    src: nuevodirectorio
    dest: /{{item["datos"]["documentroot"]}}/
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{virtualhosts}}"
  notify: restart nginx

- name: Desactivar VirtualHost www.pagina2.org
  file:
    path: /etc/nginx/sites-enabled/pagina2.conf
    state: absent
  notify: restart nginx
